name: Noven
version: 1

libraries:
- name: tornado
  version: "3.1.1"

cron:
- description: Hoot - 7x a day
  url: backend/update
  schedule: "2 0,10,12-22/3 * * *"
- description: Warm - 2x a day
  url: backend/update
  schedule: "2 12,20 * * *"
- description: Cool - 1x a day
  url: backend/update
  schedule: "2 18 * * *"
- description: Cold - 1x every 8 day
  url: backend/update
  schedule: "2 12 */8 * *"

handlers:
- url: /static/
  gzip: on
