name: Noven
version: 1

libraries:
- name: tornado
  version: "2.4.1"

cron:
- description: Update schedule for 1nd term.
  url: backend/update
  schedule: "2 0,8,10,12-22/3 * 1-2 *"
- description: Update schedule for 2nd term.
  url: backend/update
  schedule: "2 0,8,10,12-22/3 * 6-7 *"

handlers:
- url: /static/
  gzip: on
