name: Noven
version: 1

libraries:
- name: tornado
  version: "2.4.1"

cron:
- description: Red
  url: backend/update
  schedule: "2 0,8,10,12-22/3 * 1,2,6,7 *"
- description: Orange
  url: backend/update
  schedule: "2 0 * 3,8,9,12 *"
- description: Green
  url: backend/update
  schedule: "2 0 */6 4,5,10,11 *"

handlers:
- url: /static/
  gzip: on
