name: Noven
version: 1

libraries:
- name: tornado
  version: "3.1.1"

cron:
- description: Hot
  url: backend/update
  schedule: "2 0,10,12-22/3 * 1,2,7 *"
- description: Warm
  url: backend/update
  schedule: "2 18 * 3,6,8,9,12 *"
- description: Chill
  url: backend/update
  schedule: "2 12 */8 4,5,10,11 *"

handlers:
- url: /static/
  gzip: on
